/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'removeExercise' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'removeExercise' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };